name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build aplikasi
    - name: Build aplikasi
      run: npm run build

    # 5. Jalankan pengujian
    - name: Run tests
      run: npm test
